export type AgeGroup = 'junior' | 'intermediate' | 'senior';

export interface Level {
  id: number;
  ageGroup: AgeGroup;
  title: string;
  titleEn: string;
  concept: string;
  conceptEn: string;
  instruction: string;
  instructionEn: string;
  voiceText: string;
  voiceTextEn: string;
  hint: string;
  hintEn: string;
  gridSize: number;
  startPos: { x: number; y: number };
  startDir: 'NORTH' | 'EAST' | 'SOUTH' | 'WEST';
  targets: { x: number; y: number }[];
  obstacles: { x: number; y: number }[];
  allowedBlocks: {
    moveForward?: boolean;
    turnLeft?: boolean;
    turnRight?: boolean;
    collectItem?: boolean;
    repeat?: boolean;
    condition?: boolean;
  };
  optimalBlocks: number;
}

export const LEVELS: Level[] = [
  // ==========================================
  // JUNIOR TRACK (Ages 5–7): 5 Levels
  // ==========================================
  {
    id: 1,
    ageGroup: 'junior',
    title: 'स्तर 1: पहला कदम',
    titleEn: 'Level 1: First Step',
    concept: 'सीधी रेखा (Sequence)',
    conceptEn: 'Linear Sequence',
    instruction: 'बंदर को सीधा आगे बढ़ाकर केला उठाएं।',
    instructionEn: 'Move the monkey straight ahead to collect the banana.',
    voiceText: 'बंदर को आगे ले जाएं और केला उठाएं।',
    voiceTextEn: 'Move monkey forward and collect the banana.',
    hint: '2 बार "आगे बढ़ो" और "केला उठाओ" ब्लॉक लगाएं।',
    hintEn: 'Attach 2 "Move Forward" blocks and 1 "Collect Banana" block.',
    gridSize: 5,
    startPos: { x: 1, y: 2 },
    startDir: 'EAST',
    targets: [{ x: 3, y: 2 }],
    obstacles: [],
    allowedBlocks: { moveForward: true, collectItem: true },
    optimalBlocks: 3,
  },
  {
    id: 2,
    ageGroup: 'junior',
    title: 'स्तर 2: दायाँ मोड़',
    titleEn: 'Level 2: Right Turn',
    concept: 'दायाँ मोड़ (Right Turn)',
    conceptEn: 'Right Turn',
    instruction: 'आगे बढ़ें और केला लेने के लिए दाएँ मुड़ें।',
    instructionEn: 'Move forward and turn right to collect the banana.',
    voiceText: 'आगे बढ़ें और दाएँ मुड़ें।',
    voiceTextEn: 'Move forward and turn right.',
    hint: 'आगे बढ़ो, दाएँ मुड़ो, आगे बढ़ो और केला उठाओ।',
    hintEn: 'Move forward, turn right, move forward, and collect banana.',
    gridSize: 5,
    startPos: { x: 1, y: 1 },
    startDir: 'EAST',
    targets: [{ x: 2, y: 3 }],
    obstacles: [],
    allowedBlocks: { moveForward: true, turnRight: true, collectItem: true },
    optimalBlocks: 5,
  },
  {
    id: 3,
    ageGroup: 'junior',
    title: 'स्तर 3: बायाँ मोड़',
    titleEn: 'Level 3: Left Turn',
    concept: 'बायाँ मोड़ (Left Turn)',
    conceptEn: 'Left Turn',
    instruction: 'आगे बढ़ें और केला लेने के लिए बाएँ मुड़ें।',
    instructionEn: 'Move forward and turn left to reach the banana.',
    voiceText: 'आगे बढ़ें और बाएँ मुड़ें।',
    voiceTextEn: 'Move forward and turn left.',
    hint: 'आगे बढ़ो, बाएँ मुड़ो, 2 कदम आगे और केला उठाओ।',
    hintEn: 'Move forward, turn left, move forward 2 steps, and collect banana.',
    gridSize: 5,
    startPos: { x: 1, y: 3 },
    startDir: 'EAST',
    targets: [{ x: 2, y: 1 }],
    obstacles: [],
    allowedBlocks: { moveForward: true, turnLeft: true, collectItem: true },
    optimalBlocks: 5,
  },
  {
    id: 4,
    ageGroup: 'junior',
    title: 'स्तर 4: दोनों मोड़',
    titleEn: 'Level 4: Both Turns',
    concept: 'दिशा नियंत्रण (Left & Right)',
    conceptEn: 'Direction Control',
    instruction: 'बाएँ और दाएँ दोनों मोड़ों का उपयोग करके फल तक पहुँचें।',
    instructionEn: 'Use both left and right turns to reach the fruit.',
    voiceText: 'बाएँ और दाएँ दोनों मोड़ों का उपयोग करें।',
    voiceTextEn: 'Use both left and right turns to reach the banana.',
    hint: 'आगे बढ़ो, बाएँ मुड़ो, आगे बढ़ो, दाएँ मुड़ो और केला उठाओ।',
    hintEn: 'Move forward, turn left, move forward, turn right, and collect.',
    gridSize: 5,
    startPos: { x: 0, y: 3 },
    startDir: 'EAST',
    targets: [{ x: 3, y: 1 }],
    obstacles: [],
    allowedBlocks: { moveForward: true, turnLeft: true, turnRight: true, collectItem: true },
    optimalBlocks: 6,
  },
  {
    id: 5,
    ageGroup: 'junior',
    title: 'स्तर 5: पत्थर से बचो',
    titleEn: 'Level 5: Avoid the Rock',
    concept: 'सरल रुकावट (Obstacle)',
    conceptEn: 'Obstacle Avoidance',
    instruction: 'रास्ते में पत्थर 🪨 है! ऊपर से घूमकर केला उठाएं।',
    instructionEn: 'There is a rock 🪨 ahead! Steer around it to get the banana.',
    voiceText: 'पत्थर से बचकर सुरक्षित केला उठाएं।',
    voiceTextEn: 'Navigate around the rock safely to collect the banana.',
    hint: 'बाएँ मुड़कर पत्थर के ऊपर से रास्ता बनाएं।',
    hintEn: 'Turn left to route around the rock safely.',
    gridSize: 5,
    startPos: { x: 0, y: 2 },
    startDir: 'EAST',
    targets: [{ x: 4, y: 2 }],
    obstacles: [{ x: 2, y: 2 }],
    allowedBlocks: { moveForward: true, turnLeft: true, turnRight: true, collectItem: true },
    optimalBlocks: 7,
  },

  // ==========================================
  // EXPLORER TRACK (Ages 8–10): 5 Levels
  // ==========================================
  {
    id: 6,
    ageGroup: 'intermediate',
    title: 'स्तर 1: लूप का जादू',
    titleEn: 'Level 1: Loop Magic',
    concept: 'दोहराव (Repeat Loop)',
    conceptEn: 'Repeat Loops',
    instruction: 'लंबे रास्ते के लिए "बार दोहराओ" लूप ब्लॉक का प्रयोग करें।',
    instructionEn: 'Use the "Repeat" loop block to traverse the long path.',
    voiceText: 'लंबे रास्ते के लिए दोहराव लूप ब्लॉक का प्रयोग करें।',
    voiceTextEn: 'Use a loop block to repeat steps efficiently.',
    hint: '"🔁 बार दोहराओ" में संख्या 5 डालें और अंदर "आगे बढ़ो" रखें।',
    hintEn: 'Set Repeat to 5 and place "Move Forward" inside.',
    gridSize: 7,
    startPos: { x: 0, y: 3 },
    startDir: 'EAST',
    targets: [{ x: 5, y: 3 }],
    obstacles: [],
    allowedBlocks: { moveForward: true, collectItem: true, repeat: true },
    optimalBlocks: 3,
  },
  {
    id: 7,
    ageGroup: 'intermediate',
    title: 'स्तर 2: सीढ़ीदार रास्ता',
    titleEn: 'Level 2: Staircase Pattern',
    concept: 'पैटर्न लूप (Pattern Loops)',
    conceptEn: 'Pattern Loops',
    instruction: 'सीढ़ी जैसे पैटर्न को लूप के अंदर दोहराएं।',
    instructionEn: 'Repeat the staircase sequence inside a loop.',
    voiceText: 'सीढ़ी पैटर्न को लूप में दोहराएं।',
    voiceTextEn: 'Repeat the zig-zag stairs inside the loop.',
    hint: 'लूप में [आगे बढ़ो, बाएँ मुड़ो, आगे बढ़ो, दाएँ मुड़ो] रखें।',
    hintEn: 'Inside loop: [Move Forward, Turn Left, Move Forward, Turn Right].',
    gridSize: 7,
    startPos: { x: 1, y: 5 },
    startDir: 'EAST',
    targets: [{ x: 5, y: 1 }],
    obstacles: [{ x: 1, y: 4 }, { x: 2, y: 3 }, { x: 3, y: 2 }, { x: 4, y: 1 }],
    allowedBlocks: { moveForward: true, turnLeft: true, turnRight: true, collectItem: true, repeat: true },
    optimalBlocks: 6,
  },
  {
    id: 8,
    ageGroup: 'intermediate',
    title: 'स्तर 3: दोहरे फल',
    titleEn: 'Level 3: Two Bananas',
    concept: 'बहु-लक्ष्य लूप (Multi-Target)',
    conceptEn: 'Multi-Target Loops',
    instruction: 'लूप और मोड़ों का प्रयोग कर दोनों केले 🍌 इकट्ठा करें!',
    instructionEn: 'Use loops and turns to collect both bananas 🍌!',
    voiceText: 'दोनों केले इकट्ठा करें।',
    voiceTextEn: 'Collect both bananas using loops.',
    hint: 'पहले सीधा जाकर पहला केला लें, फिर मुड़कर दूसरा केला लें।',
    hintEn: 'Head straight to collect the first banana, then turn for the second.',
    gridSize: 7,
    startPos: { x: 1, y: 1 },
    startDir: 'EAST',
    targets: [{ x: 4, y: 1 }, { x: 4, y: 4 }],
    obstacles: [{ x: 2, y: 2 }],
    allowedBlocks: { moveForward: true, turnLeft: true, turnRight: true, collectItem: true, repeat: true },
    optimalBlocks: 7,
  },
  {
    id: 9,
    ageGroup: 'intermediate',
    title: 'स्तर 4: भूलभुलैया (Mini Maze)',
    titleEn: 'Level 4: Mini Maze',
    concept: 'पथ योजना (Maze Navigation)',
    conceptEn: 'Maze Navigation',
    instruction: 'पत्थरों के बीच से सही रास्ता निकालें।',
    instructionEn: 'Navigate carefully through the maze of rocks.',
    voiceText: 'पत्थरों के बीच से सही रास्ता निकालें।',
    voiceTextEn: 'Find the clear path between the rocks.',
    hint: 'पत्थरों की कतार से बचते हुए आगे बढ़ें।',
    hintEn: 'Steer clear of the rock walls.',
    gridSize: 7,
    startPos: { x: 0, y: 1 },
    startDir: 'EAST',
    targets: [{ x: 5, y: 5 }],
    obstacles: [
      { x: 2, y: 0 }, { x: 2, y: 1 }, { x: 2, y: 2 },
      { x: 4, y: 4 }, { x: 4, y: 5 }, { x: 4, y: 6 },
    ],
    allowedBlocks: { moveForward: true, turnLeft: true, turnRight: true, collectItem: true, repeat: true },
    optimalBlocks: 8,
  },
  {
    id: 10,
    ageGroup: 'intermediate',
    title: 'स्तर 5: चौकोर चक्कर',
    titleEn: 'Level 5: Square Perimeter',
    concept: 'लूप परिक्रमा (Square Loop)',
    conceptEn: 'Square Loop Orbit',
    instruction: 'चारों तरफ घूमकर कोने का फल प्राप्त करें।',
    instructionEn: 'Loop around the perimeter to collect the corner fruit.',
    voiceText: 'चारों तरफ घूमकर फल प्राप्त करें।',
    voiceTextEn: 'Loop around to collect the fruit.',
    hint: 'लूप का प्रयोग करके मुड़ने और चलने का चक्र बनाएं।',
    hintEn: 'Construct a repeat cycle of moving forward and turning.',
    gridSize: 7,
    startPos: { x: 1, y: 1 },
    startDir: 'EAST',
    targets: [{ x: 1, y: 2 }],
    obstacles: [{ x: 2, y: 2 }, { x: 2, y: 3 }, { x: 3, y: 2 }],
    allowedBlocks: { moveForward: true, turnLeft: true, turnRight: true, collectItem: true, repeat: true },
    optimalBlocks: 6,
  },

  // ==========================================
  // RESEARCHER TRACK (Ages 11+): 5 Levels
  // ==========================================
  {
    id: 11,
    ageGroup: 'senior',
    title: 'स्तर 1: अगर आगे पत्थर हो',
    titleEn: 'Level 1: If Rock Ahead',
    concept: 'शर्त निर्देश (If Condition)',
    conceptEn: 'If-Conditions',
    instruction: 'अगर आगे पत्थर आए तो मुड़ें, अन्यथा सीधे बढ़ें।',
    instructionEn: 'If there is a rock ahead, turn; otherwise, move straight.',
    voiceText: 'अगर आगे पत्थर हो तो मुड़ें।',
    voiceTextEn: 'Turn if you detect a rock ahead.',
    hint: '"❓ अगर आगे पत्थर हो" ब्लॉक के अंदर "बाएँ मुड़ो" रखें।',
    hintEn: 'Put "Turn Left" inside the "If Rock Ahead" block.',
    gridSize: 7,
    startPos: { x: 1, y: 3 },
    startDir: 'EAST',
    targets: [{ x: 3, y: 1 }],
    obstacles: [{ x: 3, y: 3 }],
    allowedBlocks: { moveForward: true, turnLeft: true, turnRight: true, collectItem: true, condition: true },
    optimalBlocks: 5,
  },
  {
    id: 12,
    ageGroup: 'senior',
    title: 'स्तर 2: स्वचालित रोबोट',
    titleEn: 'Level 2: Autonomous Bot',
    concept: 'लूप + शर्त (Loop + Condition)',
    conceptEn: 'Loops with Conditions',
    instruction: 'लूप के अंदर आगे बढ़ें और पत्थर आते ही सुरक्षित दिशा में मुड़ें।',
    instructionEn: 'Move inside a loop and turn safely whenever a rock appears.',
    voiceText: 'लूप और शर्त का एक साथ प्रयोग करें।',
    voiceTextEn: 'Combine loops with conditional branches.',
    hint: 'लूप में "आगे बढ़ो" और "अगर आगे पत्थर हो तो दाएँ मुड़ो" लगाएं।',
    hintEn: 'In loop: "Move Forward" + "If Rock Ahead, Turn Right".',
    gridSize: 7,
    startPos: { x: 0, y: 2 },
    startDir: 'EAST',
    targets: [{ x: 4, y: 5 }],
    obstacles: [{ x: 4, y: 2 }],
    allowedBlocks: { moveForward: true, turnLeft: true, turnRight: true, collectItem: true, repeat: true, condition: true },
    optimalBlocks: 6,
  },
  {
    id: 13,
    ageGroup: 'senior',
    title: 'स्तर 3: दोहरी बाधा शर्त',
    titleEn: 'Level 3: Multi-Obstacle Condition',
    concept: 'एकाधिक स्थितियाँ (Complex Conditions)',
    conceptEn: 'Complex Path Logic',
    instruction: 'रास्ते में कई बाधाएं हैं! शर्त ब्लॉक से बंदर को सही मार्ग दिखाएं।',
    instructionEn: 'Multiple obstacles in the path! Use condition blocks to navigate.',
    voiceText: 'शर्त ब्लॉक से बंदर को सही मार्ग दिखाएं।',
    voiceTextEn: 'Use conditions to avoid obstacles.',
    hint: 'पत्थर पहचानकर समय पर मुड़ने के निर्देश दें।',
    hintEn: 'Inspect for obstacles and execute turns proactively.',
    gridSize: 7,
    startPos: { x: 1, y: 1 },
    startDir: 'EAST',
    targets: [{ x: 5, y: 3 }],
    obstacles: [{ x: 3, y: 1 }, { x: 5, y: 2 }],
    allowedBlocks: { moveForward: true, turnLeft: true, turnRight: true, collectItem: true, repeat: true, condition: true },
    optimalBlocks: 7,
  },
  {
    id: 14,
    ageGroup: 'senior',
    title: 'स्तर 4: तीन फलों का संग्रह',
    titleEn: 'Level 4: Three-Target Optimization',
    concept: 'पूर्ण तर्क एवं अनुकूलन (Optimization)',
    conceptEn: 'Algorithm Optimization',
    instruction: 'सभी 3 फल इकट्ठा करें! लूप और शर्त की मदद से कम से कम ब्लॉक उपयोग करें।',
    instructionEn: 'Collect all 3 fruits using the fewest blocks possible.',
    voiceText: 'तीनों फल इकट्ठा करें।',
    voiceTextEn: 'Collect all 3 fruits with an optimal program.',
    hint: 'पहले किनारे के दो फल, फिर बीच का फल लें।',
    hintEn: 'Target the outer fruits first, then the inner one.',
    gridSize: 7,
    startPos: { x: 0, y: 0 },
    startDir: 'EAST',
    targets: [{ x: 4, y: 0 }, { x: 4, y: 4 }, { x: 0, y: 4 }],
    obstacles: [{ x: 2, y: 2 }, { x: 2, y: 3 }],
    allowedBlocks: { moveForward: true, turnLeft: true, turnRight: true, collectItem: true, repeat: true, condition: true },
    optimalBlocks: 9,
  },
  {
    id: 15,
    ageGroup: 'senior',
    title: 'स्तर 5: मास्टर रिसर्चर 🎓',
    titleEn: 'Level 5: Master Researcher 🎓',
    concept: 'मास्टर स्तर (Capstone Challenge)',
    conceptEn: 'Capstone Challenge',
    instruction: 'भूलभुलैया पार करें, सभी फल लें और Young Researcher सर्टिफिकेट जीतें!',
    instructionEn: 'Solve the grand maze, collect all items, and earn your certificate!',
    voiceText: 'अंतिम चुनौती! सभी फल इकट्ठा करें और जीतें!',
    voiceTextEn: 'Final challenge! Complete the maze and win!',
    hint: 'लूप, शर्त और सही मोड़ों का पूर्ण संयोजन बनाएं।',
    hintEn: 'Assemble the complete combination of loops, conditions, and turns.',
    gridSize: 7,
    startPos: { x: 0, y: 0 },
    startDir: 'EAST',
    targets: [{ x: 6, y: 0 }, { x: 6, y: 6 }, { x: 0, y: 6 }],
    obstacles: [
      { x: 2, y: 1 }, { x: 2, y: 2 }, { x: 2, y: 3 },
      { x: 4, y: 3 }, { x: 4, y: 4 }, { x: 4, y: 5 },
    ],
    allowedBlocks: { moveForward: true, turnLeft: true, turnRight: true, collectItem: true, repeat: true, condition: true },
    optimalBlocks: 10,
  },
];