export type AgeGroup = 'junior' | 'intermediate' | 'senior';

export interface Level {
  id: number;
  ageGroup: AgeGroup;
  title: string;
  concept: string;
  instruction: string;
  voiceText: string;
  hint: string;
  gridSize: number;
  startPos: { x: number; y: number };
  startDir: 'NORTH' | 'EAST' | 'SOUTH' | 'WEST';
  targets: { x: number; y: number }[];
  obstacles: { x: number; y: number }[];
  allowedBlocks: {
    moveForward?: boolean;
    turnLeft?: boolean;
    turnRight?: boolean;
    collectItem?: boolean;
    repeat?: boolean;
    condition?: boolean;
  };
  optimalBlocks: number;
}

export const LEVELS: Level[] = [
  // ==========================================
  // JUNIOR TRACK (Ages 5–7): 5 Levels
  // ==========================================
  {
    id: 1,
    ageGroup: 'junior',
    title: 'स्तर 1: पहला कदम',
    concept: 'सीधी रेखा (Sequence)',
    instruction: 'बंदर को सीधा आगे बढ़ाकर केला उठाएं।',
    voiceText: 'बंदर को आगे ले जाएं और केला उठाएं।',
    hint: '2 बार "आगे बढ़ो" और "केला उठाओ" ब्लॉक लगाएं।',
    gridSize: 5,
    startPos: { x: 1, y: 2 },
    startDir: 'EAST',
    targets: [{ x: 3, y: 2 }],
    obstacles: [],
    allowedBlocks: { moveForward: true, collectItem: true },
    optimalBlocks: 3,
  },
  {
    id: 2,
    ageGroup: 'junior',
    title: 'स्तर 2: दायाँ मोड़',
    concept: 'दायाँ मोड़ (Right Turn)',
    instruction: 'आगे बढ़ें और केला लेने के लिए दाएँ मुड़ें।',
    voiceText: 'आगे बढ़ें और दाएँ मुड़ें।',
    hint: 'आगे बढ़ो, दाएँ मुड़ो, आगे बढ़ो और केला उठाओ।',
    gridSize: 5,
    startPos: { x: 1, y: 1 },
    startDir: 'EAST',
    targets: [{ x: 2, y: 3 }],
    obstacles: [],
    allowedBlocks: { moveForward: true, turnRight: true, collectItem: true },
    optimalBlocks: 5,
  },
  {
    id: 3,
    ageGroup: 'junior',
    title: 'स्तर 3: बायाँ मोड़',
    concept: 'बायाँ मोड़ (Left Turn)',
    instruction: 'आगे बढ़ें और केला लेने के लिए बाएँ मुड़ें।',
    voiceText: 'आगे बढ़ें और बाएँ मुड़ें।',
    hint: 'आगे बढ़ो, बाएँ मुड़ो, 2 कदम आगे और केला उठाओ।',
    gridSize: 5,
    startPos: { x: 1, y: 3 },
    startDir: 'EAST',
    targets: [{ x: 2, y: 1 }],
    obstacles: [],
    allowedBlocks: { moveForward: true, turnLeft: true, collectItem: true },
    optimalBlocks: 5,
  },
  {
    id: 4,
    ageGroup: 'junior',
    title: 'स्तर 4: दोनों मोड़',
    concept: 'दिशा नियंत्रण (Left & Right)',
    instruction: 'बाएँ और दाएँ दोनों मोड़ों का उपयोग करके फल तक पहुँचें।',
    voiceText: 'बाएँ और दाएँ दोनों मोड़ों का उपयोग करें।',
    hint: 'आगे बढ़ो, बाएँ मुड़ो, आगे बढ़ो, दाएँ मुड़ो और केला उठाओ।',
    gridSize: 5,
    startPos: { x: 0, y: 3 },
    startDir: 'EAST',
    targets: [{ x: 3, y: 1 }],
    obstacles: [],
    allowedBlocks: { moveForward: true, turnLeft: true, turnRight: true, collectItem: true },
    optimalBlocks: 6,
  },
  {
    id: 5,
    ageGroup: 'junior',
    title: 'स्तर 5: पत्थर से बचो',
    concept: 'सरल रुकावट (Obstacle)',
    instruction: 'रास्ते में पत्थर 🪨 है! ऊपर से घूमकर केला उठाएं।',
    voiceText: 'पत्थर से बचकर सुरक्षित केला उठाएं।',
    hint: 'बाएँ मुड़कर पत्थर के ऊपर से रास्ता बनाएं।',
    gridSize: 5,
    startPos: { x: 0, y: 2 },
    startDir: 'EAST',
    targets: [{ x: 4, y: 2 }],
    obstacles: [{ x: 2, y: 2 }],
    allowedBlocks: { moveForward: true, turnLeft: true, turnRight: true, collectItem: true },
    optimalBlocks: 7,
  },

  // ==========================================
  // EXPLORER TRACK (Ages 8–10): 5 Levels
  // ==========================================
  {
    id: 6,
    ageGroup: 'intermediate',
    title: 'स्तर 1: लूप का जादू',
    concept: 'दोहराव (Repeat Loop)',
    instruction: 'लंबे रास्ते के लिए "बार दोहराओ" लूप ब्लॉक का प्रयोग करें।',
    voiceText: 'लंबे रास्ते के लिए दोहराव लूप ब्लॉक का प्रयोग करें।',
    hint: '"🔁 बार दोहराओ" में संख्या 5 डालें और अंदर "आगे बढ़ो" रखें।',
    gridSize: 7,
    startPos: { x: 0, y: 3 },
    startDir: 'EAST',
    targets: [{ x: 5, y: 3 }],
    obstacles: [],
    allowedBlocks: { moveForward: true, collectItem: true, repeat: true },
    optimalBlocks: 3,
  },
  {
    id: 7,
    ageGroup: 'intermediate',
    title: 'स्तर 2: सीढ़ीदार रास्ता',
    concept: 'पैटर्न लूप (Pattern Loops)',
    instruction: 'सीढ़ी जैसे पैटर्न को लूप के अंदर दोहराएं।',
    voiceText: 'सीढ़ी पैटर्न को लूप में दोहराएं।',
    hint: 'लूप में [आगे बढ़ो, बाएँ मुड़ो, आगे बढ़ो, दाएँ मुड़ो] रखें।',
    gridSize: 7,
    startPos: { x: 1, y: 5 },
    startDir: 'EAST',
    targets: [{ x: 5, y: 1 }],
    obstacles: [{ x: 1, y: 4 }, { x: 2, y: 3 }, { x: 3, y: 2 }, { x: 4, y: 1 }],
    allowedBlocks: { moveForward: true, turnLeft: true, turnRight: true, collectItem: true, repeat: true },
    optimalBlocks: 6,
  },
  {
    id: 8,
    ageGroup: 'intermediate',
    title: 'स्तर 3: दोहरे फल',
    concept: 'बहु-लक्ष्य लूप (Multi-Target)',
    instruction: 'लूप और मोड़ों का प्रयोग कर दोनों केले 🍌 इकट्ठा करें!',
    voiceText: 'दोनों केले इकट्ठा करें।',
    hint: 'पहले सीधा जाकर पहला केला लें, फिर मुड़कर दूसरा केला लें।',
    gridSize: 7,
    startPos: { x: 1, y: 1 },
    startDir: 'EAST',
    targets: [{ x: 4, y: 1 }, { x: 4, y: 4 }],
    obstacles: [{ x: 2, y: 2 }],
    allowedBlocks: { moveForward: true, turnLeft: true, turnRight: true, collectItem: true, repeat: true },
    optimalBlocks: 7,
  },
  {
    id: 9,
    ageGroup: 'intermediate',
    title: 'स्तर 4: भूलभुलैया (Mini Maze)',
    concept: 'पथ योजना (Maze Navigation)',
    instruction: 'पत्थरों के बीच से सही रास्ता निकालें।',
    voiceText: 'पत्थरों के बीच से सही रास्ता निकालें।',
    hint: 'पत्थरों की कतार से बचते हुए आगे बढ़ें।',
    gridSize: 7,
    startPos: { x: 0, y: 1 },
    startDir: 'EAST',
    targets: [{ x: 5, y: 5 }],
    obstacles: [
      { x: 2, y: 0 }, { x: 2, y: 1 }, { x: 2, y: 2 },
      { x: 4, y: 4 }, { x: 4, y: 5 }, { x: 4, y: 6 },
    ],
    allowedBlocks: { moveForward: true, turnLeft: true, turnRight: true, collectItem: true, repeat: true },
    optimalBlocks: 8,
  },
  {
    id: 10,
    ageGroup: 'intermediate',
    title: 'स्तर 5: चौकोर चक्कर',
    concept: 'लूप परिक्रमा (Square Loop)',
    instruction: 'चारों तरफ घूमकर कोने का फल प्राप्त करें।',
    voiceText: 'चारों तरफ घूमकर फल प्राप्त करें।',
    hint: 'लूप का प्रयोग करके मुड़ने और चलने का चक्र बनाएं।',
    gridSize: 7,
    startPos: { x: 1, y: 1 },
    startDir: 'EAST',
    targets: [{ x: 1, y: 2 }],
    obstacles: [{ x: 2, y: 2 }, { x: 2, y: 3 }, { x: 3, y: 2 }],
    allowedBlocks: { moveForward: true, turnLeft: true, turnRight: true, collectItem: true, repeat: true },
    optimalBlocks: 6,
  },

  // ==========================================
  // RESEARCHER TRACK (Ages 11+): 5 Levels
  // ==========================================
  {
    id: 11,
    ageGroup: 'senior',
    title: 'स्तर 1: अगर आगे पत्थर हो',
    concept: 'शर्त निर्देश (If Condition)',
    instruction: 'अगर आगे पत्थर आए तो मुड़ें, अन्यथा सीधे बढ़ें।',
    voiceText: 'अगर आगे पत्थर हो तो मुड़ें।',
    hint: '"❓ अगर आगे पत्थर हो" ब्लॉक के अंदर "बाएँ मुड़ो" रखें।',
    gridSize: 7,
    startPos: { x: 1, y: 3 },
    startDir: 'EAST',
    targets: [{ x: 3, y: 1 }],
    obstacles: [{ x: 3, y: 3 }],
    allowedBlocks: { moveForward: true, turnLeft: true, turnRight: true, collectItem: true, condition: true },
    optimalBlocks: 5,
  },
  {
    id: 12,
    ageGroup: 'senior',
    title: 'स्तर 2: स्वचालित रोबोट',
    concept: 'लूप + शर्त (Loop + Condition)',
    instruction: 'लूप के अंदर आगे बढ़ें और पत्थर आते ही सुरक्षित दिशा में मुड़ें।',
    voiceText: 'लूप और शर्त का एक साथ प्रयोग करें।',
    hint: 'लूप में "आगे बढ़ो" और "अगर आगे पत्थर हो तो दाएँ मुड़ो" लगाएं।',
    gridSize: 7,
    startPos: { x: 0, y: 2 },
    startDir: 'EAST',
    targets: [{ x: 4, y: 5 }],
    obstacles: [{ x: 4, y: 2 }],
    allowedBlocks: { moveForward: true, turnLeft: true, turnRight: true, collectItem: true, repeat: true, condition: true },
    optimalBlocks: 6,
  },
  {
    id: 13,
    ageGroup: 'senior',
    title: 'स्तर 3: दोहरी बाधा शर्त',
    concept: 'एकाधिक स्थितियाँ (Complex Conditions)',
    instruction: 'रास्ते में कई बाधाएं हैं! शर्त ब्लॉक से बंदर को सही मार्ग दिखाएं।',
    voiceText: 'शर्त ब्लॉक से बंदर को सही मार्ग दिखाएं।',
    hint: 'पत्थर पहचानकर समय पर मुड़ने के निर्देश दें।',
    gridSize: 7,
    startPos: { x: 1, y: 1 },
    startDir: 'EAST',
    targets: [{ x: 5, y: 3 }],
    obstacles: [{ x: 3, y: 1 }, { x: 5, y: 2 }],
    allowedBlocks: { moveForward: true, turnLeft: true, turnRight: true, collectItem: true, repeat: true, condition: true },
    optimalBlocks: 7,
  },
  {
    id: 14,
    ageGroup: 'senior',
    title: 'स्तर 4: तीन फलों का संग्रह',
    concept: 'पूर्ण तर्क एवं अनुकूलन (Optimization)',
    instruction: 'सभी 3 फल इकट्ठा करें! लूप और शर्त की मदद से कम से कम ब्लॉक उपयोग करें।',
    voiceText: 'तीनों फल इकट्ठा करें।',
    hint: 'पहले किनारे के दो फल, फिर बीच का फल लें।',
    gridSize: 7,
    startPos: { x: 0, y: 0 },
    startDir: 'EAST',
    targets: [{ x: 4, y: 0 }, { x: 4, y: 4 }, { x: 0, y: 4 }],
    obstacles: [{ x: 2, y: 2 }, { x: 2, y: 3 }],
    allowedBlocks: { moveForward: true, turnLeft: true, turnRight: true, collectItem: true, repeat: true, condition: true },
    optimalBlocks: 9,
  },
  {
    id: 15,
    ageGroup: 'senior',
    title: 'स्तर 5: मास्टर रिसर्चर 🎓',
    concept: 'मास्टर स्तर (Capstone Challenge)',
    instruction: 'भूलभुलैया पार करें, सभी फल लें और Young Researcher सर्टिफिकेट जीतें!',
    voiceText: 'अंतिम चुनौती! सभी फल इकट्ठा करें और जीतें!',
    hint: 'लूप, शर्त और सही मोड़ों का पूर्ण संयोजन बनाएं।',
    gridSize: 7,
    startPos: { x: 0, y: 0 },
    startDir: 'EAST',
    targets: [{ x: 6, y: 0 }, { x: 6, y: 6 }, { x: 0, y: 6 }],
    obstacles: [
      { x: 2, y: 1 }, { x: 2, y: 2 }, { x: 2, y: 3 },
      { x: 4, y: 3 }, { x: 4, y: 4 }, { x: 4, y: 5 },
    ],
    allowedBlocks: { moveForward: true, turnLeft: true, turnRight: true, collectItem: true, repeat: true, condition: true },
    optimalBlocks: 10,
  },
];